/**
 * Embeds coin rotation SVGs into the bundle so WonderCoin works without HTTP fetches
 * (Metro vs API host, Android cleartext, tunnel, etc.).
 *
 * Run from app/:  node scripts/genWonderCoinFrames.cjs
 */
const fs = require('fs')
const path = require('path')

const APP_ROOT = path.join(__dirname, '..')
const COIN_DIR = path.join(APP_ROOT, 'public', 'homepageimgs', 'Coinrotation')
const OUT = path.join(APP_ROOT, 'src', 'components', 'wonderCoinFrames.generated.ts')

const FRAME_FILES = [
  'CoinFRONT.svg',
  'Coin2.svg',
  'Coin3.svg',
  'Coin4.svg',
  'Coin5.svg',
  'Coin6.svg',
  'Coin7.svg',
  'Coin8.svg',
  'Coin9.svg',
  'Coin10.svg',
  'Coin11.svg',
  'Coin12.svg',
  'Coin13.svg',
  'Coin14.svg',
  'Coin15.svg',
  'Coin16.svg',
  'Coin17.svg',
  'Coin18.svg',
  'Coin19.svg',
  'Coin20.svg',
  'Coin21.svg',
  'Coin22.svg',
  'Coin23.svg',
  'Coin24.svg',
  'Coin25.svg',
  'Coin26.svg',
  'Coin27.svg',
  'Coin28.svg',
  'Coin29.svg',
  'Coin30.svg',
  'Coin31.svg',
  'Coin32.svg',
]

function main() {
  if (!fs.existsSync(COIN_DIR)) {
    console.error('Missing coin dir:', COIN_DIR)
    process.exit(1)
  }
  const parts = []
  parts.push('/** Auto-generated by scripts/genWonderCoinFrames.cjs — do not edit */')
  parts.push('')
  const frameStrings = []
  for (const name of FRAME_FILES) {
    const fp = path.join(COIN_DIR, name)
    if (!fs.existsSync(fp)) {
      console.error('Missing file:', fp)
      process.exit(1)
    }
    const raw = fs.readFileSync(fp, 'utf8')
    frameStrings.push(JSON.stringify(raw))
  }
  parts.push(`export const WONDER_COIN_ROTATION_SVG_MARKUP = [`)
  parts.push(frameStrings.map((s) => `  ${s},`).join('\n'))
  parts.push(`] as const`)
  parts.push('')
  const frontPath = path.join(COIN_DIR, 'CoinFRONT.svg')
  const front = fs.readFileSync(frontPath, 'utf8')
  parts.push(`export const WONDER_COIN_FRONT_SVG_MARKUP: string = ${JSON.stringify(front)}`)
  parts.push('')
  fs.writeFileSync(OUT, parts.join('\n') + '\n', 'utf8')
  console.log('Wrote', OUT, `(${FRAME_FILES.length} frames + front)`)
}

main()
